const actions = {
  ADD_CART_PRODECT: "ADD_CART_PRODECT",
  REMOVE_CART_PRODECT: "REMOVE_CART_PRODECT",
  REMOVE_ALL_CART_PRODECT: "REMOVE_ALL_CART_PRODECT",
  INJECT_CART_PRODECT: "REMOVE_ALL_CART_PRODECT",
};
export default actions;
